name: Publish dashboard data
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 7 * * *"   # every day 07:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow commit back to repo
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt || true
      - name: Run pipeline and publish
        run: python scripts/run_and_publish.py
      - name: Commit & push updated docs/data
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/data/*.json
          git commit -m "Update dashboard data [skip ci]" || echo "No changes"
          git push
